apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
  namespace: simple-api
spec:
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP